# This file has been generated by ./pkgs/misc/vim-plugins/update.py. Do not edit!
{ lib, buildVimPluginFrom2Nix, fetchFromGitHub }:

final: prev:
{
  async-vim = buildVimPluginFrom2Nix {
    pname = "async-vim";
    version = "2021-03-21";
    src = fetchFromGitHub {
      owner = "prabirshrestha";
      repo = "async.vim";
      rev = "0fb846e1eb3c2bf04d52a57f41088afb3395212e";
      sha256 = "1glzg0i53wkm383y1vbddbyp1ivlsx2hivjchiw60sr9gccn8f8l";
    };
    meta.homepage = "https://github.com/prabirshrestha/async.vim/";
  };

  asyncomplete-buffer-vim = buildVimPluginFrom2Nix {
    pname = "asyncomplete-buffer-vim";
    version = "2020-06-26";
    src = fetchFromGitHub {
      owner = "prabirshrestha";
      repo = "asyncomplete-buffer.vim";
      rev = "018bcf0f712ce0fde3f1f2eaabd7004fccb2d34a";
      sha256 = "0ixc37gzgsf93sl52fa3ywz6bw7cn1406fgimmy5rz0d62b0y8yi";
    };
    meta.homepage = "https://github.com/prabirshrestha/asyncomplete-buffer.vim/";
  };

  asyncomplete-file-vim = buildVimPluginFrom2Nix {
    pname = "asyncomplete-file-vim";
    version = "2020-10-04";
    src = fetchFromGitHub {
      owner = "prabirshrestha";
      repo = "asyncomplete-file.vim";
      rev = "af59997d19c8f5ee65b448249a9cddc51560e243";
      sha256 = "1fihy0miv41xs1hfzlw4xl57qf0pih7zpp3ca8xc79rvv37ys4d9";
    };
    meta.homepage = "https://github.com/prabirshrestha/asyncomplete-file.vim/";
  };

  asyncomplete-omni-vim = buildVimPluginFrom2Nix {
    pname = "asyncomplete-omni-vim";
    version = "2021-04-11";
    src = fetchFromGitHub {
      owner = "yami-beta";
      repo = "asyncomplete-omni.vim";
      rev = "f13986b671a37d6320476af6bc066697e71463c1";
      sha256 = "191n7j0m9z5skzzvl6cdlkb7pl7n65g4wiqxdpawbicw5zk80sd4";
    };
    meta.homepage = "https://github.com/yami-beta/asyncomplete-omni.vim/";
  };

  asyncomplete-tags-vim = buildVimPluginFrom2Nix {
    pname = "asyncomplete-tags-vim";
    version = "2021-04-29";
    src = fetchFromGitHub {
      owner = "prabirshrestha";
      repo = "asyncomplete-tags.vim";
      rev = "041af0565f2c16634277cd29d2429c573af1dac4";
      sha256 = "0i1ahg96j1ixyps0lfzl7w7skd64y6br1zn3bms447341zw4lc0k";
    };
    meta.homepage = "https://github.com/prabirshrestha/asyncomplete-tags.vim/";
  };

  asyncomplete-vim = buildVimPluginFrom2Nix {
    pname = "asyncomplete-vim";
    version = "2021-05-04";
    src = fetchFromGitHub {
      owner = "prabirshrestha";
      repo = "asyncomplete.vim";
      rev = "6c653c3f8f1c1cf7a34522c9555d5160f36d29ee";
      sha256 = "1zzdybfswlh66gw8a3imkwf7m6g13rlf6dqyg71c6bfmn3zlx2l0";
    };
    meta.homepage = "https://github.com/prabirshrestha/asyncomplete.vim/";
  };

  blamer-nvim = buildVimPluginFrom2Nix {
    pname = "blamer-nvim";
    version = "2021-06-29";
    src = fetchFromGitHub {
      owner = "APZelos";
      repo = "blamer.nvim";
      rev = "12f8eea7586a91ea1994501722d2e1575d9c6b63";
      sha256 = "017x2x93g4wscw7s0m5dqhsf8hb0iv4jczbyc82mkdx8f6xg963v";
    };
    meta.homepage = "https://github.com/APZelos/blamer.nvim/";
  };

  ctrlsf-vim = buildVimPluginFrom2Nix {
    pname = "ctrlsf-vim";
    version = "2021-05-21";
    src = fetchFromGitHub {
      owner = "dyng";
      repo = "ctrlsf.vim";
      rev = "51c5b285146f042bd2015278f9b8ad74ae915e00";
      sha256 = "1901cr6sbaa8js4ylirz9p4m0r9q0a06gm71ghl6kp6pw7h5fgmq";
    };
    meta.homepage = "https://github.com/dyng/ctrlsf.vim/";
  };

  git-blame-nvim = buildVimPluginFrom2Nix {
    pname = "git-blame-nvim";
    version = "2021-06-14";
    src = fetchFromGitHub {
      owner = "f-person";
      repo = "git-blame.nvim";
      rev = "125f09f3e09091fa9cc6585156e199d08989dc0e";
      sha256 = "1d6al5yrwv0wfmy39k8ky5ha1x0a6mz6djscibwz13fvgqka2730";
    };
    meta.homepage = "https://github.com/f-person/git-blame.nvim/";
  };

  gruvbox-material = buildVimPluginFrom2Nix {
    pname = "gruvbox-material";
    version = "2021-07-29";
    src = fetchFromGitHub {
      owner = "sainnhe";
      repo = "gruvbox-material";
      rev = "7a1d276a3d938d488d2d592fbb52ecec642268fc";
      sha256 = "1pvdlci25qr122gzrb661bpl62sfz81vxsbyzwwnf16b18qsxi5r";
    };
    meta.homepage = "https://github.com/sainnhe/gruvbox-material/";
  };

  lsp_signature-nvim = buildVimPluginFrom2Nix {
    pname = "lsp_signature-nvim";
    version = "2021-07-31";
    src = fetchFromGitHub {
      owner = "ray-x";
      repo = "lsp_signature.nvim";
      rev = "933ba2f059d965ee8db288f63869b8205ea223b8";
      sha256 = "1l8qhk5d57g5kzvrxbmi6857nj38np3hzjh1dpyi3qkzdk5wnpfg";
    };
    meta.homepage = "https://github.com/ray-x/lsp_signature.nvim/";
  };

  lspsaga-nvim = buildVimPluginFrom2Nix {
    pname = "lspsaga-nvim";
    version = "2021-04-25";
    src = fetchFromGitHub {
      owner = "glepnir";
      repo = "lspsaga.nvim";
      rev = "cb0e35d2e594ff7a9c408d2e382945d56336c040";
      sha256 = "0ywhdgh6aqs0xlm8a4d9jhkik254ywagang12r5nyqxawjsmjnib";
    };
    meta.homepage = "https://github.com/glepnir/lspsaga.nvim/";
  };

  motpat-vim = buildVimPluginFrom2Nix {
    pname = "motpat-vim";
    version = "2017-11-10";
    src = fetchFromGitHub {
      owner = "Houl";
      repo = "motpat-vim";
      rev = "b127e978555282ea13b918edac2ee9ada9a4e0ec";
      sha256 = "0yjx57id4gc8bcjz3y31k77970jcpnkrghr9whb32kb85dxjrg3d";
    };
    meta.homepage = "https://github.com/Houl/motpat-vim/";
  };

  neovim-auto-autoread = buildVimPluginFrom2Nix {
    pname = "neovim-auto-autoread";
    version = "2020-07-11";
    src = fetchFromGitHub {
      owner = "thezoq2";
      repo = "neovim-auto-autoread";
      rev = "21fc7d47eaaec03f4e5ab76abacc00d8702e4590";
      sha256 = "0wyzzda5pc58xnq5rb1ik24gb5zvrzlblnb304wp7k6sqb2z21rk";
    };
    meta.homepage = "https://github.com/thezoq2/neovim-auto-autoread/";
  };

  neovim-gui-shim = buildVimPluginFrom2Nix {
    pname = "neovim-gui-shim";
    version = "2021-03-27";
    src = fetchFromGitHub {
      owner = "equalsraf";
      repo = "neovim-gui-shim";
      rev = "668188542345e682addfc816af38b7073d376a64";
      sha256 = "1s1ws7cfhg0rjfzf5clr2w6k9b8fkd57jzfna3vx1caymwspwrw2";
    };
    meta.homepage = "https://github.com/equalsraf/neovim-gui-shim/";
  };

  nerdtree = buildVimPluginFrom2Nix {
    pname = "nerdtree";
    version = "2021-07-15";
    src = fetchFromGitHub {
      owner = "preservim";
      repo = "nerdtree";
      rev = "2c14ed0e153cdcd0a1c7d1eabec6820bb6b3f8a2";
      sha256 = "0gny5xw4knvjlkgazygpkwy8fk2x8igh45f980ypjghfkiw8h5f8";
    };
    meta.homepage = "https://github.com/preservim/nerdtree/";
  };

  nerdtree-git-plugin = buildVimPluginFrom2Nix {
    pname = "nerdtree-git-plugin";
    version = "2021-07-28";
    src = fetchFromGitHub {
      owner = "Xuyuanp";
      repo = "nerdtree-git-plugin";
      rev = "ff9b14f14dceecb6c08cb05053ad649c3b6ac250";
      sha256 = "1q2zjbg3j4j4746ljp2ccssgp2sykrn3zp4kyc9n0hlqaiwmhbm9";
    };
    meta.homepage = "https://github.com/Xuyuanp/nerdtree-git-plugin/";
  };

  nvim-lspconfig = buildVimPluginFrom2Nix {
    pname = "nvim-lspconfig";
    version = "2021-07-28";
    src = fetchFromGitHub {
      owner = "neovim";
      repo = "nvim-lspconfig";
      rev = "3df7c2afa4e6e5c9e9c9f85ab275837248ed7db4";
      sha256 = "16krk21g2r45h9hds2jpgplchqzcqgpqg6pdw89pvzx3b5qazab2";
    };
    meta.homepage = "https://github.com/neovim/nvim-lspconfig/";
  };

  nvim-tree-lua = buildVimPluginFrom2Nix {
    pname = "nvim-tree-lua";
    version = "2021-07-19";
    src = fetchFromGitHub {
      owner = "kyazdani42";
      repo = "nvim-tree.lua";
      rev = "d3e76b81e5b169af192dea4da0bd6f64faad2c36";
      sha256 = "0hw50yyikndx1260a50j6izjsa4m709r7v3qzrpwz482d7fq700j";
    };
    meta.homepage = "https://github.com/kyazdani42/nvim-tree.lua/";
  };

  nvim-web-devicons = buildVimPluginFrom2Nix {
    pname = "nvim-web-devicons";
    version = "2021-07-27";
    src = fetchFromGitHub {
      owner = "kyazdani42";
      repo = "nvim-web-devicons";
      rev = "80ec3ba1aa3fd4005c4679b7b03da37435bc1654";
      sha256 = "1pmg2qp6sdk2ijcav4s1la1zax05cwd9vvbrr3s283lqsqwzflax";
    };
    meta.homepage = "https://github.com/kyazdani42/nvim-web-devicons/";
  };

  omnisharp-vim = buildVimPluginFrom2Nix {
    pname = "omnisharp-vim";
    version = "2021-07-16";
    src = fetchFromGitHub {
      owner = "OmniSharp";
      repo = "omnisharp-vim";
      rev = "390c8880f6c6d2a3ba24f18c045770aba39d126f";
      sha256 = "1i19996h92dx5c6v9hmv62cg0y3a20ph2wv94r7fqf9db0izlcf7";
      fetchSubmodules = true;
    };
    meta.homepage = "https://github.com/OmniSharp/omnisharp-vim/";
  };

  python-mode = buildVimPluginFrom2Nix {
    pname = "python-mode";
    version = "2018-04-29";
    src = fetchFromGitHub {
      owner = "python-mode";
      repo = "python-mode";
      rev = "f94b0d7b21714f950f5878b430fbfde21c3b7ad9";
      sha256 = "0zxsa1agigzb9adrwq54pdyl984drdqzz3kkixaijkq77kkdvj0n";
    };
    meta.homepage = "https://github.com/python-mode/python-mode/";
  };

  sonokai = buildVimPluginFrom2Nix {
    pname = "sonokai";
    version = "2021-07-29";
    src = fetchFromGitHub {
      owner = "sainnhe";
      repo = "sonokai";
      rev = "f4f43c13af9d1dfb5bbe7c43d76de27d2af2d1cd";
      sha256 = "1yqqgckjg7hr8q33q49rxf678crl8dk9avs56h9yrgi0f8zs90qk";
    };
    meta.homepage = "https://github.com/sainnhe/sonokai/";
  };

  vim-conque = buildVimPluginFrom2Nix {
    pname = "vim-conque";
    version = "2021-06-25";
    src = fetchFromGitHub {
      owner = "goballooning";
      repo = "vim-conque";
      rev = "a9a9186899974d8aa13732a544322b55aef00cf1";
      sha256 = "0qmvj8mlyvnmm3fzqk7v8nfs5gil9alnmx2i3c63y0w4gyr5axi0";
    };
    meta.homepage = "https://github.com/goballooning/vim-conque/";
  };

  vim-ctrlspace = buildVimPluginFrom2Nix {
    pname = "vim-ctrlspace";
    version = "2021-07-12";
    src = fetchFromGitHub {
      owner = "vim-ctrlspace";
      repo = "vim-ctrlspace";
      rev = "ec4bd1074d0542a615d862a676db1e1ecaa5495d";
      sha256 = "1czg6n14gd28b58qighrh8piybd6vs80d19v2nvk3l9dvgihip5m";
    };
    meta.homepage = "https://github.com/vim-ctrlspace/vim-ctrlspace/";
  };

  vim-fakeclip = buildVimPluginFrom2Nix {
    pname = "vim-fakeclip";
    version = "2020-05-19";
    src = fetchFromGitHub {
      owner = "kana";
      repo = "vim-fakeclip";
      rev = "59858dabdb55787d7f047c4ab26b45f11ebb533b";
      sha256 = "1jrfi1vc7svhypvg2gizx40vracr91m9d912b61j0c7z8swix908";
    };
    meta.homepage = "https://github.com/kana/vim-fakeclip/";
  };

  vim-hashicorp-tools = buildVimPluginFrom2Nix {
    pname = "vim-hashicorp-tools";
    version = "2021-02-11";
    src = fetchFromGitHub {
      owner = "hashivim";
      repo = "vim-hashicorp-tools";
      rev = "4a81618e15abe90448aa62284f71992135a98131";
      sha256 = "1yad6spf0lidkgpxz8xf1xwgyar4w83qmb10yp1wprs8l8dyan04";
    };
    meta.homepage = "https://github.com/hashivim/vim-hashicorp-tools/";
  };

  vim-monokai-tasty = buildVimPluginFrom2Nix {
    pname = "vim-monokai-tasty";
    version = "2021-05-27";
    src = fetchFromGitHub {
      owner = "patstockwell";
      repo = "vim-monokai-tasty";
      rev = "efc71525a74999e66e4f37ae1599ccd5ee66c7fc";
      sha256 = "17br8d25ikfjmryycfp6jq4ns30b0gqr9z6xrkcfldf1q6ydzwhf";
    };
    meta.homepage = "https://github.com/patstockwell/vim-monokai-tasty/";
  };

  vim-pasta = buildVimPluginFrom2Nix {
    pname = "vim-pasta";
    version = "2018-09-08";
    src = fetchFromGitHub {
      owner = "sickill";
      repo = "vim-pasta";
      rev = "cb4501a123d74fc7d66ac9f10b80c9d393746c66";
      sha256 = "14rswwx24i75xzgkbx1hywan1msn2ki26353ly2pyvznnqss1pwq";
    };
    meta.homepage = "https://github.com/sickill/vim-pasta/";
  };

  vim-perforce = buildVimPluginFrom2Nix {
    pname = "vim-perforce";
    version = "2020-02-05";
    src = fetchFromGitHub {
      owner = "nfvs";
      repo = "vim-perforce";
      rev = "d1dcbe8aca797976678200f42cc2994b7f6c86c2";
      sha256 = "027qcj4y8iywy90izdwifk76rf2wsvhg2iv16f906ya6jxfmkd09";
    };
    meta.homepage = "https://github.com/nfvs/vim-perforce/";
  };

  vim-solarized8 = buildVimPluginFrom2Nix {
    pname = "vim-solarized8";
    version = "2021-04-24";
    src = fetchFromGitHub {
      owner = "lifepillar";
      repo = "vim-solarized8";
      rev = "28b81a4263054f9584a98f94cca3e42815d44725";
      sha256 = "0vq0fxsdy0mk2zpbd1drrrxnbd44r39gqzp0s71vh9q4bnww7jds";
    };
    meta.homepage = "https://github.com/lifepillar/vim-solarized8/";
  };

  Workspace-Manager = buildVimPluginFrom2Nix {
    pname = "Workspace-Manager";
    version = "2010-10-18";
    src = fetchFromGitHub {
      owner = "vim-scripts";
      repo = "Workspace-Manager";
      rev = "f16076629c8d382fbd9b1f136f31209ba6602d68";
      sha256 = "06z1z8q1jkdqaz7gsfwcl2rndxcgqacsawhs84w0p9wvmsqra5c9";
    };
    meta.homepage = "https://github.com/vim-scripts/Workspace-Manager/";
  };

}
