# GENERATED by ./pkgs/applications/editors/vim/plugins/update.py. Do not edit!
{ lib, buildVimPlugin, buildNeovimPlugin, fetchFromGitHub, fetchgit }:

final: prev:
{
  ChatGPT-nvim = buildVimPlugin {
    pname = "ChatGPT.nvim";
    version = "2024-08-26";
    src = fetchFromGitHub {
      owner = "jackMort";
      repo = "ChatGPT.nvim";
      rev = "4d9d297c2409c8ebc715da7f1d7705a221564555";
      sha256 = "0i4ras7n66i4h64bb0v70v85b70d0rw33hy16kgyr20b6qkm53vm";
    };
    meta.homepage = "https://github.com/jackMort/ChatGPT.nvim/";
  };

  LuaSnip = buildVimPlugin {
    pname = "LuaSnip";
    version = "2024-09-12";
    src = fetchFromGitHub {
      owner = "L3MON4D3";
      repo = "LuaSnip";
      rev = "e808bee352d1a6fcf902ca1a71cee76e60e24071";
      sha256 = "1yf50bwcg94bprbczcki7c1n318m6ar99m8h1yrmn6m0w4cbvf8r";
      fetchSubmodules = true;
    };
    meta.homepage = "https://github.com/L3MON4D3/LuaSnip/";
  };

  alpha-nvim = buildVimPlugin {
    pname = "alpha-nvim";
    version = "2024-09-30";
    src = fetchFromGitHub {
      owner = "goolord";
      repo = "alpha-nvim";
      rev = "bf3c8bb8c02ed3d9644cc5bbc48e2bdc39349cd7";
      sha256 = "0d1yrranhin6hmg77v81q0wa4xj4y1bfn2a4s6l33qa2zly62yfz";
    };
    meta.homepage = "https://github.com/goolord/alpha-nvim/";
  };

  bufferline-nvim = buildVimPlugin {
    pname = "bufferline.nvim";
    version = "2024-07-18";
    src = fetchFromGitHub {
      owner = "akinsho";
      repo = "bufferline.nvim";
      rev = "0b2fd861eee7595015b6561dade52fb060be10c4";
      sha256 = "068gg98w88q0j3c1wrlggsp0986yppa8vlbnzy7wy4g7kn0aqfsn";
    };
    meta.homepage = "https://github.com/akinsho/bufferline.nvim/";
  };

  cmp-buffer = buildVimPlugin {
    pname = "cmp-buffer";
    version = "2022-08-10";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-buffer";
      rev = "3022dbc9166796b644a841a02de8dd1cc1d311fa";
      sha256 = "1cwx8ky74633y0bmqmvq1lqzmphadnhzmhzkddl3hpb7rgn18vkl";
    };
    meta.homepage = "https://github.com/hrsh7th/cmp-buffer/";
  };

  cmp-cmdline = buildVimPlugin {
    pname = "cmp-cmdline";
    version = "2024-03-22";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-cmdline";
      rev = "d250c63aa13ead745e3a40f61fdd3470efde3923";
      sha256 = "1sh4ar3ky4qikh2brlwy9nmhy3208fs77ysbgvhccj0lx2krf6c8";
    };
    meta.homepage = "https://github.com/hrsh7th/cmp-cmdline/";
  };

  cmp-nvim-lsp = buildVimPlugin {
    pname = "cmp-nvim-lsp";
    version = "2024-05-17";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-nvim-lsp";
      rev = "39e2eda76828d88b773cc27a3f61d2ad782c922d";
      sha256 = "13zcw6c7zppvbsjlr8yj3vml6ayalvhjbbqszljmn1f9hmkpwg89";
    };
    meta.homepage = "https://github.com/hrsh7th/cmp-nvim-lsp/";
  };

  cmp-nvim-lsp-signature-help = buildVimPlugin {
    pname = "cmp-nvim-lsp-signature-help";
    version = "2024-05-17";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-nvim-lsp-signature-help";
      rev = "031e6ba70b0ad5eee49fd2120ff7a2e325b17fa7";
      sha256 = "08ipis3agyiaiqn91lq6imsnwyhqpadah7aj1v47v12ycy923cxl";
    };
    meta.homepage = "https://github.com/hrsh7th/cmp-nvim-lsp-signature-help/";
  };

  cmp-path = buildVimPlugin {
    pname = "cmp-path";
    version = "2022-10-03";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-path";
      rev = "91ff86cd9c29299a64f968ebb45846c485725f23";
      sha256 = "18ixx14ibc7qrv32nj0ylxrx8w4ggg49l5vhcqd35hkp4n56j6mn";
    };
    meta.homepage = "https://github.com/hrsh7th/cmp-path/";
  };

  cmp-rg = buildVimPlugin {
    pname = "cmp-rg";
    version = "2023-09-01";
    src = fetchFromGitHub {
      owner = "lukas-reineke";
      repo = "cmp-rg";
      rev = "677a7874ee8f1afc648c2e7d63a97bc21a7663c5";
      sha256 = "0cahyz5i6iyjqb4cklrkimw5pjajfnlazpmky617ysl3m1b6pwk3";
    };
    meta.homepage = "https://github.com/lukas-reineke/cmp-rg/";
  };

  cmp-spell = buildVimPlugin {
    pname = "cmp-spell";
    version = "2024-05-07";
    src = fetchFromGitHub {
      owner = "f3fora";
      repo = "cmp-spell";
      rev = "694a4e50809d6d645c1ea29015dad0c293f019d6";
      sha256 = "0qh86jbm1a843lc9p5z4gqarzpwq4vbb8cjlg7jn87ighx5cgzhr";
    };
    meta.homepage = "https://github.com/f3fora/cmp-spell/";
  };

  cmp-treesitter = buildVimPlugin {
    pname = "cmp-treesitter";
    version = "2024-05-13";
    src = fetchFromGitHub {
      owner = "ray-x";
      repo = "cmp-treesitter";
      rev = "958fcfa0d8ce46d215e19cc3992c542f576c4123";
      sha256 = "05as01c2f7i20zkzpqbq9n8ji9bcwd678ixmxnrz9vmz5zsj8q7i";
    };
    meta.homepage = "https://github.com/ray-x/cmp-treesitter/";
  };

  cmp-vsnip = buildVimPlugin {
    pname = "cmp-vsnip";
    version = "2022-11-22";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-vsnip";
      rev = "989a8a73c44e926199bfd05fa7a516d51f2d2752";
      sha256 = "1hs1gv7q0vfn82pwdwpy46nsi4n5z6yljnzl0rpvwfp8g79hssfs";
    };
    meta.homepage = "https://github.com/hrsh7th/cmp-vsnip/";
  };

  cmp_luasnip = buildVimPlugin {
    pname = "cmp_luasnip";
    version = "2023-10-09";
    src = fetchFromGitHub {
      owner = "saadparwaiz1";
      repo = "cmp_luasnip";
      rev = "05a9ab28b53f71d1aece421ef32fee2cb857a843";
      sha256 = "0gw3jz65dnxkc618j26zj37gs1yycf7wql9yqc9glazjdjbljhlx";
    };
    meta.homepage = "https://github.com/saadparwaiz1/cmp_luasnip/";
  };

  filetype-nvim = buildVimPlugin {
    pname = "filetype.nvim";
    version = "2024-05-06";
    src = fetchFromGitHub {
      owner = "nathom";
      repo = "filetype.nvim";
      rev = "15891eb2b138d54b08aef793c43901910ec6879f";
      sha256 = "0a5xkhqk83234ls6p2i694hkb0mb2r33alkrrkkcq6i49zdfl3hp";
    };
    meta.homepage = "https://github.com/nathom/filetype.nvim/";
  };

  friendly-snippets = buildVimPlugin {
    pname = "friendly-snippets";
    version = "2024-09-23";
    src = fetchFromGitHub {
      owner = "rafamadriz";
      repo = "friendly-snippets";
      rev = "00ba9dd3df89509f95437b8d595553707c46d5ea";
      sha256 = "0nc6pflj81qldg4yjywzww4md0315kdj0jv8sbcfi8m7kdbjwfy9";
    };
    meta.homepage = "https://github.com/rafamadriz/friendly-snippets/";
  };

  galaxyline-nvim = buildVimPlugin {
    pname = "galaxyline.nvim";
    version = "2023-01-08";
    src = fetchFromGitHub {
      owner = "nvimdev";
      repo = "galaxyline.nvim";
      rev = "20f5f750002532a35193f55cd499074fc97d933d";
      sha256 = "06f7q8c3izvzv5alsxdpx6afrn7bq8g3d4z4am3c3zrsbggfa02a";
    };
    meta.homepage = "https://github.com/nvimdev/galaxyline.nvim/";
  };

  git-blame-vim = buildVimPlugin {
    pname = "git-blame.vim";
    version = "2019-08-02";
    src = fetchFromGitHub {
      owner = "zivyangll";
      repo = "git-blame.vim";
      rev = "9d144b7bed5d8f1c9259551768b7f3b3d1294917";
      sha256 = "06zb5xcc59k25rpwl46j82fcqckiznmj97v6i0mwlb8jhqqrhy9j";
    };
    meta.homepage = "https://github.com/zivyangll/git-blame.vim/";
  };

  gitsigns-nvim = buildNeovimPlugin {
    pname = "gitsigns.nvim";
    version = "2024-09-27";
    src = fetchFromGitHub {
      owner = "lewis6991";
      repo = "gitsigns.nvim";
      rev = "863903631e676b33e8be2acb17512fdc1b80b4fb";
      sha256 = "15mp1yh989njsj6fmklr4vxgzkbj4lmwzrgjqayqdf687vpkjrm3";
    };
    meta.homepage = "https://github.com/lewis6991/gitsigns.nvim/";
  };

  gruvbox-nvim = buildVimPlugin {
    pname = "gruvbox.nvim";
    version = "2024-10-01";
    src = fetchFromGitHub {
      owner = "ellisonleao";
      repo = "gruvbox.nvim";
      rev = "49d9c0b150ba70efcd831ec7b3cb8ee740067045";
      sha256 = "0vjwqyw4y6hf6qyjpap04f6z6lbgha98hizils77rg3msaw1jj7y";
    };
    meta.homepage = "https://github.com/ellisonleao/gruvbox.nvim/";
  };

  hlchunk-nvim = buildVimPlugin {
    pname = "hlchunk.nvim";
    version = "2024-10-02";
    src = fetchFromGitHub {
      owner = "shellRaining";
      repo = "hlchunk.nvim";
      rev = "ba6e2347177fec8ec6af4ae26d11a468c9e0ca72";
      sha256 = "01j09706vwdha1hpg6az0zi8wr0in0gmzklbzii7z2796yk687j7";
    };
    meta.homepage = "https://github.com/shellRaining/hlchunk.nvim/";
  };

  image-nvim = buildNeovimPlugin {
    pname = "image.nvim";
    version = "2024-01-07";
    src = fetchFromGitHub {
      owner = "samodostal";
      repo = "image.nvim";
      rev = "acbd1d7d64ac0643021a6146eb0557e7c2e793d0";
      sha256 = "0s5fxlc7igmvgpmpry1vkrl4xav37cx94ay1sg246y7y2j4j5l56";
    };
    meta.homepage = "https://github.com/samodostal/image.nvim/";
  };

  lsp_signature-nvim = buildVimPlugin {
    pname = "lsp_signature.nvim";
    version = "2024-09-16";
    src = fetchFromGitHub {
      owner = "ray-x";
      repo = "lsp_signature.nvim";
      rev = "fc38521ea4d9ec8dbd4c2819ba8126cea743943b";
      sha256 = "0ag79vvjz1dqyw9358ijdkckr1rqshxkpk5fl0kww1vl3pfwv9jv";
    };
    meta.homepage = "https://github.com/ray-x/lsp_signature.nvim/";
  };

  lspkind-nvim = buildVimPlugin {
    pname = "lspkind.nvim";
    version = "2024-09-26";
    src = fetchFromGitHub {
      owner = "onsails";
      repo = "lspkind.nvim";
      rev = "59c3f419af48a2ffb2320cea85e44e5a95f71664";
      sha256 = "18wwvclabimlhn8c4l4jp63waarm5vql1qmzg1s6y6lfbq1zss7g";
    };
    meta.homepage = "https://github.com/onsails/lspkind.nvim/";
  };

  lspsaga-nvim = buildVimPlugin {
    pname = "lspsaga.nvim";
    version = "2024-09-10";
    src = fetchFromGitHub {
      owner = "nvimdev";
      repo = "lspsaga.nvim";
      rev = "e64351d0e6335eadf089aa2b9f17221e54ca10a4";
      sha256 = "0n8jmfg7rg23skdd4qlqyx78acww6ahskd3j6l5k2lvh5jlxjc4r";
    };
    meta.homepage = "https://github.com/nvimdev/lspsaga.nvim/";
  };

  lush-nvim = buildNeovimPlugin {
    pname = "lush.nvim";
    version = "2024-08-16";
    src = fetchFromGitHub {
      owner = "rktjmp";
      repo = "lush.nvim";
      rev = "45a79ec4acb5af783a6a29673a999ce37f00497e";
      sha256 = "0ac93sdhsi41hpwpshffpkvj5c3kklflsy0pln77743x69g05rcr";
    };
    meta.homepage = "https://github.com/rktjmp/lush.nvim/";
  };

  motpat-vim = buildVimPlugin {
    pname = "motpat-vim";
    version = "2017-11-10";
    src = fetchFromGitHub {
      owner = "Houl";
      repo = "motpat-vim";
      rev = "b127e978555282ea13b918edac2ee9ada9a4e0ec";
      sha256 = "0yjx57id4gc8bcjz3y31k77970jcpnkrghr9whb32kb85dxjrg3d";
    };
    meta.homepage = "https://github.com/Houl/motpat-vim/";
  };

  multicursor-nvim = buildVimPlugin {
    pname = "multicursor.nvim";
    version = "2024-10-04";
    src = fetchFromGitHub {
      owner = "jake-stewart";
      repo = "multicursor.nvim";
      rev = "bf03c70d8eb0372bb7ce0215ef3d513601b6daa9";
      sha256 = "1xbq6haqr0siwc8dplzq6apnb1mdilial44z49fgn5xc58p0di2g";
    };
    meta.homepage = "https://github.com/jake-stewart/multicursor.nvim/";
  };

  neo-tree-nvim = buildVimPlugin {
    pname = "neo-tree.nvim";
    version = "2024-09-17";
    src = fetchFromGitHub {
      owner = "nvim-neo-tree";
      repo = "neo-tree.nvim";
      rev = "a77af2e764c5ed4038d27d1c463fa49cd4794e07";
      sha256 = "02ag3h40p5ga12y1fwbcd06nnl3rb0l5hs064ylpkx2kjcl79arf";
    };
    meta.homepage = "https://github.com/nvim-neo-tree/neo-tree.nvim/";
  };

  neovim-auto-autoread = buildVimPlugin {
    pname = "neovim-auto-autoread";
    version = "2020-07-11";
    src = fetchFromGitHub {
      owner = "thezoq2";
      repo = "neovim-auto-autoread";
      rev = "21fc7d47eaaec03f4e5ab76abacc00d8702e4590";
      sha256 = "0wyzzda5pc58xnq5rb1ik24gb5zvrzlblnb304wp7k6sqb2z21rk";
    };
    meta.homepage = "https://github.com/thezoq2/neovim-auto-autoread/";
  };

  neovim-gui-shim = buildVimPlugin {
    pname = "neovim-gui-shim";
    version = "2024-08-25";
    src = fetchFromGitHub {
      owner = "equalsraf";
      repo = "neovim-gui-shim";
      rev = "4d10bf3f68b9c0903bd1d9e456571d1d2ec16fde";
      sha256 = "00iqbz8ax0wijc6fq818v3dh3d7yjr1zwq4c0larhdjja9adbxmi";
    };
    meta.homepage = "https://github.com/equalsraf/neovim-gui-shim/";
  };

  neovim-session-manager = buildVimPlugin {
    pname = "neovim-session-manager";
    version = "2024-08-02";
    src = fetchFromGitHub {
      owner = "Shatur";
      repo = "neovim-session-manager";
      rev = "cbaebd92dce84e9ba63cb07d3199e5a19b204c1a";
      sha256 = "03xma7y6c4qwcwlyzrsp8l0c1rmp3qyi1qw4wrdrdsvijc3mnwqy";
    };
    meta.homepage = "https://github.com/Shatur/neovim-session-manager/";
  };

  noice-nvim = buildVimPlugin {
    pname = "noice.nvim";
    version = "2024-10-02";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "noice.nvim";
      rev = "df448c649ef6bc5a6a633a44f2ad0ed8d4442499";
      sha256 = "1qsnvg41wmvx9gip11lka21gq04f59ydm0x3pdri99irbqzy0azn";
    };
    meta.homepage = "https://github.com/folke/noice.nvim/";
  };

  novim-mode = buildVimPlugin {
    pname = "novim-mode";
    version = "2023-04-16";
    src = fetchFromGitHub {
      owner = "tombh";
      repo = "novim-mode";
      rev = "9a8e839eef60ebe5a9ed417879baafa64ca9d666";
      sha256 = "1rfvshnimrwl5bkiqnkp2rm8k20x74lj5ggjxa1axy6wam60q7kw";
    };
    meta.homepage = "https://github.com/tombh/novim-mode/";
  };

  nui-nvim = buildNeovimPlugin {
    pname = "nui.nvim";
    version = "2024-09-15";
    src = fetchFromGitHub {
      owner = "MunifTanjim";
      repo = "nui.nvim";
      rev = "b58e2bfda5cea347c9d58b7f11cf3012c7b3953f";
      sha256 = "0klz9wy09jk74f39v6f7s5gn98nf3vq4lgv5d29mkszpykxaligp";
    };
    meta.homepage = "https://github.com/MunifTanjim/nui.nvim/";
  };

  null-ls-nvim = buildVimPlugin {
    pname = "null-ls.nvim";
    version = "2023-08-12";
    src = fetchFromGitHub {
      owner = "jose-elias-alvarez";
      repo = "null-ls.nvim";
      rev = "0010ea927ab7c09ef0ce9bf28c2b573fc302f5a7";
      sha256 = "00nkg77y9mp7ac46bdcaga36bbbrwbp7k1d6ajjgg9qf76pk8q3i";
    };
    meta.homepage = "https://github.com/jose-elias-alvarez/null-ls.nvim/";
  };

  nvim-cmp = buildNeovimPlugin {
    pname = "nvim-cmp";
    version = "2024-08-01";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "nvim-cmp";
      rev = "ae644feb7b67bf1ce4260c231d1d4300b19c6f30";
      sha256 = "0fk7s6apvq4r9h82jqm5azf1zg9aklyycgh7ivnb98bw9a0ivjim";
    };
    meta.homepage = "https://github.com/hrsh7th/nvim-cmp/";
  };

  nvim-colorizer-lua = buildVimPlugin {
    pname = "nvim-colorizer.lua";
    version = "2024-09-11";
    src = fetchFromGitHub {
      owner = "NvChad";
      repo = "nvim-colorizer.lua";
      rev = "0671e0eabc6842676d3310370e8fae4e1c51d7f9";
      sha256 = "1ilxfiq76a7wzh4nvhds5b7k6q2shrnfmyb4icnfc8w0kx1vby0m";
    };
    meta.homepage = "https://github.com/NvChad/nvim-colorizer.lua/";
  };

  nvim-hlslens = buildVimPlugin {
    pname = "nvim-hlslens";
    version = "2024-09-21";
    src = fetchFromGitHub {
      owner = "kevinhwang91";
      repo = "nvim-hlslens";
      rev = "07afd4dd14405ad14b142a501a3abea6ae44b21b";
      sha256 = "12nf1jj7z4h7nqi6gmk768z8hcl4qdgi4rpwj0y8frawc2f75ixv";
    };
    meta.homepage = "https://github.com/kevinhwang91/nvim-hlslens/";
  };

  nvim-lspconfig = buildVimPlugin {
    pname = "nvim-lspconfig";
    version = "2024-10-04";
    src = fetchFromGitHub {
      owner = "neovim";
      repo = "nvim-lspconfig";
      rev = "c9ac9613ad627f52c9387e4f8bd4625b75788c90";
      sha256 = "1rliz16gf1j80yw5kh20h5b4s7da6yp1c6pmg3pwn3gph38ms0kr";
    };
    meta.homepage = "https://github.com/neovim/nvim-lspconfig/";
  };

  nvim-notify = buildVimPlugin {
    pname = "nvim-notify";
    version = "2024-09-22";
    src = fetchFromGitHub {
      owner = "rcarriga";
      repo = "nvim-notify";
      rev = "fbef5d32be8466dd76544a257d3f3dce20082a07";
      sha256 = "0wbsib27kgrk632c094ivjbc8rw51kbalq9c8j576p78k93wipj9";
    };
    meta.homepage = "https://github.com/rcarriga/nvim-notify/";
  };

  nvim-scrollbar = buildVimPlugin {
    pname = "nvim-scrollbar";
    version = "2024-06-03";
    src = fetchFromGitHub {
      owner = "petertriho";
      repo = "nvim-scrollbar";
      rev = "d09f14aa16c9f2748e77008f9da7b1f76e4e7b85";
      sha256 = "1zm0xaph29hk2dw4rpmpz67nxxbr39f67zfil5gwyzk3d87q56k3";
    };
    meta.homepage = "https://github.com/petertriho/nvim-scrollbar/";
  };

  nvim-surround = buildVimPlugin {
    pname = "nvim-surround";
    version = "2024-06-24";
    src = fetchFromGitHub {
      owner = "kylechui";
      repo = "nvim-surround";
      rev = "ec2dc7671067e0086cdf29c2f5df2dd909d5f71f";
      sha256 = "1d5ffrsl1ryiq8nzxx7k69gpin6zs2ys4zc5pg47qcpazx7my8qc";
    };
    meta.homepage = "https://github.com/kylechui/nvim-surround/";
  };

  nvim-tree-lua = buildVimPlugin {
    pname = "nvim-tree.lua";
    version = "2024-09-30";
    src = fetchFromGitHub {
      owner = "nvim-tree";
      repo = "nvim-tree.lua";
      rev = "c9104a5d079db5a158c9562c54689df27d52dccc";
      sha256 = "0k1j4rnp9fz4ph92ph5ia3i3n1jm4f5gsffjc1kdglp9lmdil885";
    };
    meta.homepage = "https://github.com/nvim-tree/nvim-tree.lua/";
  };

  nvim-treesitter = buildVimPlugin {
    pname = "nvim-treesitter";
    version = "2024-10-03";
    src = fetchFromGitHub {
      owner = "nvim-treesitter";
      repo = "nvim-treesitter";
      rev = "cc2c11c403a9143827501223b4ee64432dcaf246";
      sha256 = "0zn05ldy626a1ayvapmr3spr9r4isdjkfww8n37rqscyqh0vwm2k";
    };
    meta.homepage = "https://github.com/nvim-treesitter/nvim-treesitter/";
  };

  nvim-treesitter-context = buildVimPlugin {
    pname = "nvim-treesitter-context";
    version = "2024-10-03";
    src = fetchFromGitHub {
      owner = "nvim-treesitter";
      repo = "nvim-treesitter-context";
      rev = "63374d1c36050fdea7a773aa4125b45e9a8da8f5";
      sha256 = "1wxrvz5fizl3s6hm3ag3lvqd920knfh6kvn44pdqzh2r2qn8ffki";
    };
    meta.homepage = "https://github.com/nvim-treesitter/nvim-treesitter-context/";
  };

  nvim-treesitter-textobjects = buildVimPlugin {
    pname = "nvim-treesitter-textobjects";
    version = "2024-09-27";
    src = fetchFromGitHub {
      owner = "nvim-treesitter";
      repo = "nvim-treesitter-textobjects";
      rev = "4a2d05ec24eaa6b655c7d19092a3b6c0219d46b9";
      sha256 = "1a41b8klxz9rassb2v2ij74d719knj2c4zxi3ppkr1m5l533lnzc";
    };
    meta.homepage = "https://github.com/nvim-treesitter/nvim-treesitter-textobjects/";
  };

  nvim-web-devicons = buildVimPlugin {
    pname = "nvim-web-devicons";
    version = "2024-09-30";
    src = fetchFromGitHub {
      owner = "nvim-tree";
      repo = "nvim-web-devicons";
      rev = "6b53401918a9033a41159d012160c5fb5eb249ae";
      sha256 = "1bncyvmx5x0ic8xi2bw533lvgzkghiwfkiy4ir2rbhcq4c579j1g";
    };
    meta.homepage = "https://github.com/nvim-tree/nvim-web-devicons/";
  };

  omnisharp-vim = buildVimPlugin {
    pname = "omnisharp-vim";
    version = "2023-10-15";
    src = fetchFromGitHub {
      owner = "OmniSharp";
      repo = "omnisharp-vim";
      rev = "f9c5d3e3375e8b5688a4506e813cb21bdc7329b1";
      sha256 = "0y4ajbipdcvdxxb4vcknkxisjfpi9qgrhkr8glpnjdb9dypf0w6g";
      fetchSubmodules = true;
    };
    meta.homepage = "https://github.com/OmniSharp/omnisharp-vim/";
  };

  parrot-nvim = buildVimPlugin {
    pname = "parrot.nvim";
    version = "2024-09-28";
    src = fetchFromGitHub {
      owner = "frankroeder";
      repo = "parrot.nvim";
      rev = "fdcaa6ccc368b69f0b0cdd8d5998e53ac2812aeb";
      sha256 = "1gn9j6x621q2rry1k0v552sg52g2inzwpag0gvjrx8zpaw45gqzr";
    };
    meta.homepage = "https://github.com/frankroeder/parrot.nvim/";
  };

  plantuml-previewer-vim = buildVimPlugin {
    pname = "plantuml-previewer.vim";
    version = "2024-09-23";
    src = fetchFromGitHub {
      owner = "weirongxu";
      repo = "plantuml-previewer.vim";
      rev = "555347700382c97b347bace57b7a9f764ed556b1";
      sha256 = "0vlx6zbdaw71vlwgs46274af60cazv6d9pa5dn9afm99vls57avq";
    };
    meta.homepage = "https://github.com/weirongxu/plantuml-previewer.vim/";
  };

  plenary-nvim = buildNeovimPlugin {
    pname = "plenary.nvim";
    version = "2024-09-17";
    src = fetchFromGitHub {
      owner = "nvim-lua";
      repo = "plenary.nvim";
      rev = "2d9b06177a975543726ce5c73fca176cedbffe9d";
      sha256 = "1blmh0qr010jhydw61kiynll2m7q4xyrvrva8b5ipf1g81x8ysbf";
    };
    meta.homepage = "https://github.com/nvim-lua/plenary.nvim/";
  };

  previm = buildVimPlugin {
    pname = "previm";
    version = "2024-05-27";
    src = fetchFromGitHub {
      owner = "previm";
      repo = "previm";
      rev = "0a3eaad218bc58af867c1a7a71b1d8323a5a7039";
      sha256 = "186ikc2i7lvaw0ssp7qyfl2p26wjgqb8v247nr52kaw26mq01r05";
    };
    meta.homepage = "https://github.com/previm/previm/";
  };

  render-markdown-nvim = buildVimPlugin {
    pname = "render-markdown.nvim";
    version = "2024-10-04";
    src = fetchFromGitHub {
      owner = "MeanderingProgrammer";
      repo = "render-markdown.nvim";
      rev = "bdf03ef2a87082ef48bb1b471d102c295e97602c";
      sha256 = "0396fp7irsjdai66is19hsjkbfw0wgfafvlgk4ypkri83s0l4if8";
    };
    meta.homepage = "https://github.com/MeanderingProgrammer/render-markdown.nvim/";
  };

  searchbox-nvim = buildVimPlugin {
    pname = "searchbox.nvim";
    version = "2024-09-04";
    src = fetchFromGitHub {
      owner = "VonHeikemen";
      repo = "searchbox.nvim";
      rev = "8dde416cabb63f6d68c8755365dcd20c65b7b3b0";
      sha256 = "0q0wv2nlvrk8k46lm096sscljmrsj7ccch7il7dp1l4fs67dl1h4";
    };
    meta.homepage = "https://github.com/VonHeikemen/searchbox.nvim/";
  };

  smart-splits-nvim = buildVimPlugin {
    pname = "smart-splits.nvim";
    version = "2024-09-27";
    src = fetchFromGitHub {
      owner = "mrjones2014";
      repo = "smart-splits.nvim";
      rev = "22ca8bf770965306082fe23dd22822134bf3b70a";
      sha256 = "0z8d2af5lx1ahly0f00y1gbd533shf9x4zinfkad8g5naajhls32";
    };
    meta.homepage = "https://github.com/mrjones2014/smart-splits.nvim/";
  };

  sonokai = buildVimPlugin {
    pname = "sonokai";
    version = "2024-09-30";
    src = fetchFromGitHub {
      owner = "sainnhe";
      repo = "sonokai";
      rev = "3dcd97c0c5e4118bc171df6ba33800dfd9524a00";
      sha256 = "026fksby6v2vl52q1n6pk4v8vrlh71cl8fjqcq4d6arz7lv2fk4j";
    };
    meta.homepage = "https://github.com/sainnhe/sonokai/";
  };

  telescope-frecency-nvim = buildVimPlugin {
    pname = "telescope-frecency.nvim";
    version = "2024-09-08";
    src = fetchFromGitHub {
      owner = "nvim-telescope";
      repo = "telescope-frecency.nvim";
      rev = "f67baca08423a6fd00167801a54db38e0b878063";
      sha256 = "197ijmyjqb27hfrxsa53x265qgfpka8997m1ndlql1wxgyz8as0g";
    };
    meta.homepage = "https://github.com/nvim-telescope/telescope-frecency.nvim/";
  };

  telescope-nvim = buildNeovimPlugin {
    pname = "telescope.nvim";
    version = "2024-09-30";
    src = fetchFromGitHub {
      owner = "nvim-telescope";
      repo = "telescope.nvim";
      rev = "eae0d8fbde590b0eaa2f9481948cd6fd7dd21656";
      sha256 = "06lqkxp7j6d6lh9pl7975214dz16zbbfq9hacrnhd6wnyq002193";
    };
    meta.homepage = "https://github.com/nvim-telescope/telescope.nvim/";
  };

  themer-lua = buildVimPlugin {
    pname = "themer.lua";
    version = "2023-10-16";
    src = fetchFromGitHub {
      owner = "themercorp";
      repo = "themer.lua";
      rev = "625510cfec70b55fe42d04b1256c5f93c92a4202";
      sha256 = "0lxkqdv4mn20pk0sn55vg543y2qfszgqbl6avypriih5j43ql77x";
    };
    meta.homepage = "https://github.com/themercorp/themer.lua/";
  };

  vim-conque = buildVimPlugin {
    pname = "vim-conque";
    version = "2021-06-25";
    src = fetchFromGitHub {
      owner = "goballooning";
      repo = "vim-conque";
      rev = "a9a9186899974d8aa13732a544322b55aef00cf1";
      sha256 = "0qmvj8mlyvnmm3fzqk7v8nfs5gil9alnmx2i3c63y0w4gyr5axi0";
    };
    meta.homepage = "https://github.com/goballooning/vim-conque/";
  };

  vim-ctrlspace = buildVimPlugin {
    pname = "vim-ctrlspace";
    version = "2024-10-03";
    src = fetchFromGitHub {
      owner = "vim-ctrlspace";
      repo = "vim-ctrlspace";
      rev = "11d01be87100272db108685fca34b48a9842d6a5";
      sha256 = "0a6iaavvbwlc3yv4aj79lay2plkz37wr9hm25pgs77d7lvvys52m";
    };
    meta.homepage = "https://github.com/vim-ctrlspace/vim-ctrlspace/";
  };

  vim-fakeclip = buildVimPlugin {
    pname = "vim-fakeclip";
    version = "2020-05-19";
    src = fetchFromGitHub {
      owner = "kana";
      repo = "vim-fakeclip";
      rev = "59858dabdb55787d7f047c4ab26b45f11ebb533b";
      sha256 = "1jrfi1vc7svhypvg2gizx40vracr91m9d912b61j0c7z8swix908";
    };
    meta.homepage = "https://github.com/kana/vim-fakeclip/";
  };

  vim-hashicorp-tools = buildVimPlugin {
    pname = "vim-hashicorp-tools";
    version = "2021-02-11";
    src = fetchFromGitHub {
      owner = "hashivim";
      repo = "vim-hashicorp-tools";
      rev = "4a81618e15abe90448aa62284f71992135a98131";
      sha256 = "1yad6spf0lidkgpxz8xf1xwgyar4w83qmb10yp1wprs8l8dyan04";
    };
    meta.homepage = "https://github.com/hashivim/vim-hashicorp-tools/";
  };

  vim-jinja2-syntax = buildVimPlugin {
    pname = "vim-jinja2-syntax";
    version = "2021-06-22";
    src = fetchFromGitHub {
      owner = "glench";
      repo = "vim-jinja2-syntax";
      rev = "2c17843b074b06a835f88587e1023ceff7e2c7d1";
      sha256 = "13mfzsw3kr3r826wkpd3jhh1sy2j10hlj1bv8n8r01hpbngikfg7";
    };
    meta.homepage = "https://github.com/glench/vim-jinja2-syntax/";
  };

  vim-pasta = buildVimPlugin {
    pname = "vim-pasta";
    version = "2023-08-12";
    src = fetchFromGitHub {
      owner = "ku1ik";
      repo = "vim-pasta";
      rev = "2b786703eef9f82ae7a56f3de4ee43e1e5efaaa5";
      sha256 = "1q4d512rq57awasb441slqp29mkzi3jxmy8clrp2s9ydwdbndwlx";
    };
    meta.homepage = "https://github.com/ku1ik/vim-pasta/";
  };

  vim-perforce = buildVimPlugin {
    pname = "vim-perforce";
    version = "2020-02-05";
    src = fetchFromGitHub {
      owner = "nfvs";
      repo = "vim-perforce";
      rev = "d1dcbe8aca797976678200f42cc2994b7f6c86c2";
      sha256 = "027qcj4y8iywy90izdwifk76rf2wsvhg2iv16f906ya6jxfmkd09";
    };
    meta.homepage = "https://github.com/nfvs/vim-perforce/";
  };

  which-key-nvim = buildVimPlugin {
    pname = "which-key.nvim";
    version = "2024-10-02";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "which-key.nvim";
      rev = "8badb359f7ab8711e2575ef75dfe6fbbd87e4821";
      sha256 = "0ylw5kp8fz7yr4j7yh4nrbl8mnqirz8rskpq0gsxr9m9fm105cbj";
    };
    meta.homepage = "https://github.com/folke/which-key.nvim/";
  };


}
